name: env-name-here-does-not-matter
channels:
  - conda-forge
  - defaults
  - bioconda
  - defaults
  - astrobiomike
dependencies:
  - python =3.7
  - pip
  - gtotree
  - muscle
  - blast
  - prodigal
  - numpy
